### ISSUE TITLE
Daniel gets annoyed too easily

### ISSUE THREAD

**Issue by haj2001** [Waingels-College/Influence-Home#1]
Daniel Milnes is infuriated by the simplest of things and anything from RAM jokes to not organizing files the way he wants them.

**Comment by haj2001** [comment]
It's true you know

**Comment by thebeanogamer** [comment]
NO!
BAD!

**Comment by haj2001** [comment]
Hello again

**Comment by haj2001** [comment]
This will not be locked!

**Comment by haj2001** [comment]
Ha ha it's still up

**Comment by haj2001** [comment]
And I can
